// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"home/web/internal/biz"
	"home/web/internal/conf"
	"home/web/internal/data"
	"home/web/internal/server"
	"home/web/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {

	captchaClient  := data.NewCaptchaClient()

	dataData, cleanup, err := data.NewData(confData, logger, captchaClient)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewCaptchaRepo(dataData, logger)
	greeterUsecase := biz.NewCaptchaUseCase(greeterRepo, logger)
	greeterService := service.NewCaptchaService(greeterUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
