server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(120.27.2.108:3306)/test
  redis:
    addr: 120.27.2.108:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
